In [1]:
import bicycleparameters as bp
from dtk.bicycle import benchmark_to_moore

In [2]:
bp_data_dir = '/Users/oliverlee/repos/BicycleParameters/data/'

In [3]:
stratos = bp.Bicycle('Stratos', bp_data_dir)
browser = bp.Bicycle('Browser', bp_data_dir)

We have foundeth a directory named: /Users/oliverlee/repos/BicycleParameters/data/bicycles/Stratos.
Found the RawData directory: /Users/oliverlee/repos/BicycleParameters/data/bicycles/Stratos/RawData
Recalcuting the parameters.
The glory of the Stratos parameters are upon you!
We have foundeth a directory named: /Users/oliverlee/repos/BicycleParameters/data/bicycles/Browser.
Found the RawData directory: /Users/oliverlee/repos/BicycleParameters/data/bicycles/Browser/RawData
Looks like you've already got some parameters for Browser, use forceRawCalc to recalculate.


In [4]:
browser.add_rider('Jason')

There is no rider on the bicycle, now adding Jason.
Loaded the precalculated parameters from /Users/oliverlee/repos/BicycleParameters/data/riders/Jason/Parameters/JasonBrowserBenchmark.txt


In [5]:
stratos.add_rider('Jason')

There is no rider on the bicycle, now adding Jason.
No parameter files found, calculating the human configuration.
Joint angle A1A2extension = 0.00213417459799 pi-rad is out of range. Must be between -1.0 and 0.0 pi-rad.
Joint angle B1B2extension = 0.00213417459799 pi-rad is out of range. Must be between -1.0 and 0.0 pi-rad.


/Users/oliverlee/miniconda3/envs/dev/lib/python3.4/site-packages/scipy/optimize/minpack.py:236: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last five Jacobian evaluations.
  warnings.warn(msg, RuntimeWarning)


In [6]:
def nominal(a):
    try:
        return a.nominal_value
    except AttributeError:
        return a

import numpy as np
vnominal = np.vectorize(nominal)

In [7]:
def print_canon_code(bicycle):
    canon = """
    private const double _m_phiphi = {};
    private const double _m_phidelta = {};
    private const double _m_deltaphi = _m_phidelta;
    private const double _m_deltadelta = {};
    private const double _c1_phiphi = 0;
    private const double _c1_phidelta = {};
    private const double _c1_deltaphi = {};
    private const double _c1_deltadelta = {};
    private const double _k0_phiphi = {};
    private const double _k0_phidelta = {};
    private const double _k0_deltaphi = _k0_phidelta;
    private const double _k0_deltadelta = {};
    private const double _k2_phiphi = 0;
    private const double _k2_phidelta = {};
    private const double _k2_deltaphi = 0;
    private const double _k2_deltadelta = {};

    """
    M, C1, K0, K2 = [vnominal(m) for m in bicycle.canonical()]
    c = canon.format(M[0, 0], M[0, 1], M[1, 1], C1[0, 1], C1[1, 0], C1[1, 1],
                     K0[0, 0], K0[0, 1], K0[1, 1], K2[0, 1], K2[1, 1])
    print(c)

In [19]:
def print_geometric_lengths(bicycle):
    lengths = """ 
    private float rR = {}f; // m
    private float rF = {}f; // m
    private float cR = {}f; // m
    private float ls = {}f; // m
    private float cF = {}f; // m
    
    public override double steerAxisTilt {{ get {{ {}; }} }}
    public override double trail {{ get {{ return {}; }} }}
    public override double wheelbase {{ get {{ return {}; }} }}
    public override double rearRadius {{ get {{ return {}; }} }}
    """
    b = bp.io.remove_uncertainties(bicycle.parameters['Benchmark'])
    d = benchmark_to_moore(b)
    print(lengths.format(d['rr'], d['rf'], d['d1'], d['d2'], d['d3'],
                         b['lam'], b['c'], b['w'], b['rR']))

In [20]:
for b in [browser, stratos]:
    print('{} + {} canonical matrices:'.format(b.bicycleName, b.riderName))
    for l, m in zip(['M', 'C1', 'K0', 'K2'], b.canonical()):
        print(l)
        print(vnominal(m))
    print('')
    print_canon_code(b)
    print_geometric_lengths(b)

Browser + Jason canonical matrices:
M
[[ 102.78260127    1.53494742]
 [   1.53494742    0.2466622 ]]
C1
[[  0.          26.39273019]
 [ -0.44980954   1.03541962]]
K0
[[-89.32195981  -1.74159477]
 [ -1.74159477  -0.67769624]]
K2
[[  0.          74.12484375]
 [  0.           1.57005903]]


    private const double _m_phiphi = 102.78260126737564;
    private const double _m_phidelta = 1.5349474185931016;
    private const double _m_deltaphi = _m_phidelta;
    private const double _m_deltadelta = 0.24666219580863546;
    private const double _c1_phiphi = 0;
    private const double _c1_phidelta = 26.39273018670496;
    private const double _c1_deltaphi = -0.4498095401132608;
    private const double _c1_deltadelta = 1.035419624597184;
    private const double _k0_phiphi = -89.32195980848145;
    private const double _k0_phidelta = -1.7415947744452318;
    private const double _k0_deltaphi = _k0_phidelta;
    private const double _k0_deltadelta = -0.6776962381761491;
    private const doubl